onboarding = false

[experimental]
kitty_graphics = true
pane_history = true

[terminal]
new_cwd = "follow"

[keys]
prefix = "alt+a"
copy_mode = "alt+v"
resize_mode = "alt+r"
detach = "alt+q"
zoom = "alt+z"
toggle_sidebar = "alt+s"

next_workspace = "prefix+n"
previous_workspace = "prefix+p"
new_worktree = "prefix+a"
remove_worktree = "prefix+x"

new_tab = "alt+c"
next_tab = "alt+n"
previous_tab = "alt+p"
rename_tab = "prefix+shift+t"

split_horizontal = "alt+;"
split_vertical = "alt+/"

focus_pane_left = "alt+h"
focus_pane_right = "alt+l"
focus_pane_up = "alt+k"
focus_pane_down = "alt+j"
swap_pane_left = "alt+left"
swap_pane_right = "alt+right"
swap_pane_up = "alt+up"
swap_pane_down = "alt+down"
close_pane = "alt+x"
rename_pane = "prefix+shift+p"

next_agent = "alt+shift+n"
previous_agent = "alt+shift+p"

[theme]
name = "vesper"
auto_switch = false

[ui]
show_agent_labels_on_pane_borders = true
prompt_new_tab_name = false
mouse_capture = true

[ui.sidebar.agents]
row_gap = 1

[ui.toast]
delivery = "herdr"
delay_seconds = 1

[ui.toast.herdr]
position = "bottom-left"


[[keys.command]]
key = "alt+g"
type = "popup"
command = "bash -l -c lazygit"
description = "run lazygit"
width="90%"
height="90%"

[[keys.command]]
key = "alt+b"
type = "popup"
command = "btop"
description = "run btop"
width="90%"
height="90%"

[[keys.command]]
key = "alt+d"
type = "popup"
command = "hunk diff"
description = "run hunk diff"
width="90%"
height="90%"

[[keys.command]]
key = "alt+f"
type = "popup"
command = "exec \"${SHELL:-sh}\""
description = "open scratch terminal"
width = "90%"
height = "90%"
