onboarding = false

[experimental]
pane_history = false

[terminal]
new_cwd = "follow"

[keys]
prefix = "alt+a"
copy_mode = "alt+v"
resize_mode = "alt+r"
detach = "alt+q"
zoom = "alt+z"
toggle_sidebar = "alt+b"

new_tab = "alt+c"
next_tab = "alt+n"
previous_tab = "alt+p"
rename_tab = "prefix+t"

split_horizontal = "alt+;"
split_vertical = "alt+/"

focus_pane_left = "alt+h"
focus_pane_right = "alt+l"
focus_pane_up = "alt+k"
focus_pane_down = "alt+j"
swap_pane_left = "alt+left"
swap_pane_right = "alt+right"
swap_pane_up = "alt+up"
swap_pane_down = "alt+down"
close_pane = "alt+x"

next_agent = "alt+shift+n"
previous_agent = "alt+shift+p"

[ui]
show_agent_labels_on_pane_borders = true
prompt_new_tab_name = false

[theme]
name = "vesper"
auto_switch = false

[ui.toast]
delivery = "herdr"

[[keys.command]]
key = "alt+g"
type = "popup"
command = "lazygit"
description = "run lazygit"
width="90%"
height="90%"
