gui:
  language: 'ja'
os:
  edit: "nvim -- {{filename}}"
  editPreset: "nvim"

git:
  diffRenderers:
    - command: >-
        hunk pager
        --mode split
    - command: >-
        hunk pager
        --mode stack
    - type: rawGit
      name: default
