set -g prefix M-a
unbind C-b

set -g base-index 1

# tmuxを256色表示できるようにする
set-option -g default-terminal screen-256color
set -g terminal-overrides 'xterm:colors=256'

# vimのキーバインドでペインを移動する
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# vimのキーバインドでペインをリサイズする
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Inherit current path
bind-key c new-window -c "#{pane_current_path}"

# | でペインを縦分割する
bind | split-window -h -c "#{pane_current_path}"

# - でペインを縦分割する
bind - split-window -v -c "#{pane_current_path}"

# コピーモードを設定する
# コピーモードでvimキーバインドを使う
setw -g mode-keys vi

# popup
bind-key M-f display-popup -d '#{pane_current_path}' -w 90% -h 90% -E
bind-key M-g display-popup -d '#{pane_current_path}' -w 90% -h 90% -E 'lazygit'

# monitor-silence のオンオフをトグルする
bind M-a if-shell "[ $(tmux show-window-options -v monitor-silence) -eq 0 ]" \
  "set-window-option monitor-silence 5; set-window-option visual-silence on; display-message 'Silence monitor ON'" \
  "set-window-option monitor-silence 0; set-window-option visual-silence off; display-message 'Silence monitor OFF'"

# List of plugins
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-sensible"
set -g @plugin "tmux-plugins/tmux-yank"
set -g @plugin "tmux-plugins/tmux-resurrect"
set -g @plugin "wfxr/tmux-power"

set -g @resurrect-save "M-s"
set -g @resurrect-restore "M-r"

# for yazi
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

run "~/.config/tmux/plugins/tpm/tpm"
